name: Release Workflow

on:
  push:
    branches:
      - release/*

jobs:
  merge_commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config --global user.email "mbuchoff@gmail.com"
        git config --global user.name "DevOps ${{ github.workflow }}"

    - name: Merge and push
      run: |
        set -e -v
        
        gitcommit=$(git rev-parse HEAD)
        git checkout release/3
        
        git merge $gitcommit --no-ff
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
