name: Release Workflow 3

on:
  push:
    branches:
      - release/*

jobs:
  merge_commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config --global user.email "mbuchoff@gmail.com"
        git config --global user.name "DevOps ${{ github.workflow }}"

    - name: Read release branch from file
      id: read_branch
      run: |
        RELEASE_BRANCH=$(cat release_branch.txt)
        echo "::set-output name=branch::${RELEASE_BRANCH}"

    - name: Merge and push
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        set -e -v
        
        gitcommit=$(git rev-parse HEAD)
        git checkout ${{ steps.read_branch.outputs.branch }}
        
        git merge $gitcommit --no-ff
        
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/mbuchoff/automerge.git
        git push origin

    - name: Trigger Secondary Workflow on Different Branch
      uses: benc-uk/workflow-dispatch@v1
      with:
        owner: ${{ github.repository_owner }}
        repo: ${{ github.event.repository.name }}
        workflow: merge-forward 2.yml
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: release/2  # Specify the target branch here
